github.com:
    users:
        waleedlugod:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: waleedlugod
